PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/aries

PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/firmware/voiceproc.img:$(TARGET_COPY_OUT_VENDOR)/firmware/voiceproc.img \
    vendor/xiaomi/aries/proprietary/vendor/firmware/voiceproc_init.img:$(TARGET_COPY_OUT_VENDOR)/firmware/voiceproc_init.img \
    vendor/xiaomi/aries/proprietary/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx132_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_default_video.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx132_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_preview.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx132_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_zsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx135_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx135_default_video.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx135_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx135_hfr_60fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx135_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx135_hfr_90fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx135_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx135_preview.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx135_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx135_video_hdr.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx135_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx135_zsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx175_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_default_video.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx175_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_hfr_120fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx175_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_hfr_60fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx175_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_hfr_90fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx175_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_preview.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_imx175_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_zsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_default_video.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_hfr.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_ov2720_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_preview.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_zsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_ov2722_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2722_default_video.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_ov2722_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2722_preview.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_ov2722_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2722_zsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_s5k3h7_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_default_video.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_s5k3h7_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_hfr_120fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_s5k3h7_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_hfr_60fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_s5k3h7_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_hfr_90fps.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_s5k3h7_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_preview.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libchromatix_s5k3h7_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_zsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libcsd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcsd-client.so \
    vendor/xiaomi/aries/proprietary/vendor/bin/efsks:$(TARGET_COPY_OUT_VENDOR)/bin/efsks \
    vendor/xiaomi/aries/proprietary/vendor/bin/fm_qsoc_patches:$(TARGET_COPY_OUT_VENDOR)/bin/fm_qsoc_patches \
    vendor/xiaomi/aries/proprietary/vendor/bin/hci_qcomm_init:$(TARGET_COPY_OUT_VENDOR)/bin/hci_qcomm_init \
    vendor/xiaomi/aries/proprietary/vendor/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    vendor/xiaomi/aries/proprietary/vendor/bin/ks:$(TARGET_COPY_OUT_VENDOR)/bin/ks \
    vendor/xiaomi/aries/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/xiaomi/aries/proprietary/vendor/bin/mpdecision:$(TARGET_COPY_OUT_VENDOR)/bin/mpdecision \
    vendor/xiaomi/aries/proprietary/vendor/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    vendor/xiaomi/aries/proprietary/vendor/bin/qcks:$(TARGET_COPY_OUT_VENDOR)/bin/qcks \
    vendor/xiaomi/aries/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    vendor/xiaomi/aries/proprietary/vendor/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd \
    vendor/xiaomi/aries/proprietary/vendor/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
    vendor/xiaomi/aries/proprietary/vendor/bin/sensors.qcom:$(TARGET_COPY_OUT_VENDOR)/bin/sensors.qcom \
    vendor/xiaomi/aries/proprietary/vendor/bin/thermal-engine:$(TARGET_COPY_OUT_VENDOR)/bin/thermal-engine \
    vendor/xiaomi/aries/proprietary/vendor/bin/thermald:$(TARGET_COPY_OUT_VENDOR)/bin/thermald \
    vendor/xiaomi/aries/proprietary/vendor/bin/time_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/time_daemon \
    vendor/xiaomi/aries/proprietary/vendor/firmware/vidc.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc.b00 \
    vendor/xiaomi/aries/proprietary/vendor/firmware/vidc.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc.b01 \
    vendor/xiaomi/aries/proprietary/vendor/firmware/vidc.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc.b02 \
    vendor/xiaomi/aries/proprietary/vendor/firmware/vidc.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc.b03 \
    vendor/xiaomi/aries/proprietary/vendor/firmware/vidc.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc.mdt \
    vendor/xiaomi/aries/proprietary/vendor/firmware/vidc_1080p.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc_1080p.fw \
    vendor/xiaomi/aries/proprietary/vendor/firmware/vidcfw.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/vidcfw.elf \
    vendor/xiaomi/aries/proprietary/vendor/etc/modem/Diag.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/modem/Diag.cfg \
    vendor/xiaomi/aries/proprietary/vendor/lib/hw/flp.msm8960.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/flp.msm8960.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/sensors.aries.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.aries.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libAKM.so:$(TARGET_COPY_OUT_VENDOR)/lib/libAKM.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libOmxAacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxAacDec.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libOmxEvrcDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxEvrcDec.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libOmxMux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxMux.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libOmxQcelp13Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxQcelp13Dec.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libOmxWmaDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxWmaDec.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTimeService.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libgemini.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgemini.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libimage-jpeg-dec-omx-comp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libimage-jpeg-enc-omx-comp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libimage-omx-common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-omx-common.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmercury.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmercury.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmcamera_frameproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_frameproc.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_image_stab.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmcamera_statsproc31.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_statsproc31.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_wavelet_lib.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmmpo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmmpo.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmmpod.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmmpod.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmmstillomx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmstillomx.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor1.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor_reg.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsensor_test.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor_test.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsensor_user_cal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor_user_cal.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalclient.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
    vendor/xiaomi/aries/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/xiaomi/aries/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglsubAndroid.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libplayback_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libplayback_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libaptXHD_encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaptXHD_encoder.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libaptX_encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaptX_encoder.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libbtnv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbtnv.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a3xx.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libc2d30.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgeofence.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libizat_core.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libloc_api_v02.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_api_v02.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libloc_ds_api.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_ds_api.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a3xx.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtime_genoff.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so

PRODUCT_PACKAGES += \
    libqminvapi \
    TimeService
